name: Deploy App on DigitalOcean

on:
  push:
    branches:
      - main
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: create env file
        run: touch .env
      - name: add variables to file
        run: echo "&{{secrets.ENV_FILE}}" > .env
      - uses: actions/checkout@v2
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: go-api
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
