name: Deploy App on DigitalOcean

on:
  push:
    branches:
      - main
      
jobs:
  create-dotenv-file:
    runs-on: ubuntu-latest
    steps:
      - name: make-envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_PORT: 8000
          envkey_DB_DRIVER: postgres
          envkey_DB_HOST: ${{secrets.DBHOST }}
          envkey_DB_USER: ${{secrets.DBUSER }}
          envkey_DB_NAME: ${{secrets.DBNAME }}
          envkey_DB_PASSWORD: ${{secrets.DBPASSWORD}}
          envkey_DB_PORT: 25060
          envkey_SSL_MODE: require
          envkey_API_SECRET: ${{secrets.APISECRET}}
          
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: go-api
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
