name: Deploy App on DigitalOcean

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */3 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: go-api
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
